"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { RiLoginBoxLine } from "react-icons/ri";
import { CgProfile } from "react-icons/cg";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    const searchInput = document.querySelector(".search-input");

    function handleFocus() {
      const audio = new Audio("/search.mp3");
      audio.play();
    }

    searchInput.addEventListener("focus", handleFocus);

    return () => {
      searchInput.removeEventListener("focus", handleFocus);
    };
  }, []);

  // 이미지 배경 변경 함수
  const changeBackground = (event) => {
    // 랜덤하게 0 or 1 선택.
    const randomIndex = Math.floor(Math.random() * 2);
    const images = ["/UK.png", "/US.png"];

    // 이미지 경로 업데이트
    const selectedImage = images[randomIndex];

    // 이미지 배경 변경
    const element = event.target;
    element.style.backgroundImage = `url(${selectedImage})`;
  };

  // 이미지 배경 안보이게 하는 함수
  const removeBackground = (event) => {
    const element = event.target;
    element.style.backgroundImage = "none";
  };

  return (
    <html lang="en">
      <body>
        {/* 상단바 */}
        <div
          className="navbar"
          style={{
            borderBottomLeftRadius: 20,
            borderBottomRightRadius: 20,
          }}
        >
          <div className="navbar-l">
            <Link href="/">
              <img src="/logo3.png" className="logo"></img>
            </Link>
            <input
              className="search-input"
              type="text"
              placeholder="도서검색"
            />
          </div>
          <div className="navbar-container">
            <div className="navbar-icon-container">
              <Link href="/domestic">
                <img src="/navbar1.png" className="navbar1-icon"></img>
              </Link>
              <Link href="/foreign">
                <img
                  src="/navbar2.png"
                  className="navbar2-icon"
                  onMouseOver={changeBackground}
                  onMouseLeave={removeBackground}
                ></img>
              </Link>
              <Link href="/japanese">
                <img src="/navbar3.png" className="navbar3-icon"></img>
              </Link>
            </div>
            <div className="navbar-title-container">
              <h4>국내도서</h4>
              <h4>영미도서</h4>
              <h4>일본도서</h4>
            </div>
          </div>
          <div className="navbar-r">
            <Link href="/sign" className="r-link">
              <RiLoginBoxLine />
              sign in
            </Link>
            <Link href="/mypage" className="r-link">
              <CgProfile />
              mypage
            </Link>
            <button>seok</button>
          </div>
        </div>
        {children}
        <div className="footer">© 2023 Read-It Mates.</div>
      </body>
    </html>
  );
}
