"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { RiLoginBoxLine } from "react-icons/ri";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    const searchInput = document.querySelector(".search-input");

    function handleFocus() {
      const audio = new Audio("/search.mp3");
      audio.play();
    }

    searchInput.addEventListener("focus", handleFocus);

    return () => {
      searchInput.removeEventListener("focus", handleFocus);
    };
  }, []);
  return (
    <html lang="en">
      <body>
        <div
          className="navbar"
          style={{ borderBottomLeftRadius: 20, borderBottomRightRadius: 20 }}
        >
          <div className="navbar-l">
            <Link href="/">
              <img src="/logo3.png" className="logo"></img>
            </Link>
            <input className="search-input" type="text" placeholder="검색" />
          </div>
          <div className="navbar-container">
            <div className="navbar-icon-container">
              <Link href="/bestSellers">
                <img src="/navbar1.png" className="navbar1-icon"></img>
              </Link>
              <Link href="/steadySellers">
                <img src="/navbar2.png" className="navbar2-icon"></img>
              </Link>
              <Link href="/">
                <img src="/navbar3.png" className="navbar3-icon"></img>
              </Link>
            </div>
            <div className="navbar-title-container">
              <h4>국내도서</h4>
              <h4>영미도서</h4>
              <h4>일본도서</h4>
            </div>
          </div>
          <div className="navbar-r">
            <Link href="/">
              <RiLoginBoxLine />
              sign in
            </Link>
            <Link href="/">mypage</Link>
            <button>seok</button>
          </div>
        </div>
        {children}
        <div className="footer">© 2023 Read-It Mates.</div>
      </body>
    </html>
  );
}
