"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { RiLoginBoxLine } from "react-icons/ri";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    const searchInput = document.querySelector(".search-input");

    function handleFocus() {
      const audio = new Audio("/search.mp3");
      audio.play();
    }

    searchInput.addEventListener("focus", handleFocus);

    return () => {
      searchInput.removeEventListener("focus", handleFocus);
    };
  }, []);
  return (
    <html lang="en">
      <body>
        <div
          className="navbar"
          style={{ borderBottomLeftRadius: 20, borderBottomRightRadius: 20 }}
        >
          <div className="navbar-l">
            <Link href="/">
              <img src="/logo3.png" className="logo"></img>
            </Link>
            <input className="search-input" type="text" placeholder="검색" />
          </div>
          <div>
            <img src="/navbar.png" className="navbar-icon"></img>
          </div>
          <div className="navbar-r">
            <Link href="/list">
              <RiLoginBoxLine />
              sign in
            </Link>
            <Link href="/list">mypage</Link>
            <button>seok</button>
          </div>
        </div>
        {children}
        <div className="footer">© 2023 Read-It Mates.</div>
      </body>
    </html>
  );
}
